// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::collections::BTreeMap;
#[allow(unused_imports)]
use sails_rs::{
    calls::{Activation, Call, Query, Remoting, RemotingAction},
    prelude::*,
    String,
};
pub struct AppFactory<R> {
    #[allow(dead_code)]
    remoting: R,
}
impl<R> AppFactory<R> {
    #[allow(unused)]
    pub fn new(remoting: R) -> Self {
        Self { remoting }
    }
}
impl<R: Remoting + Clone> traits::AppFactory for AppFactory<R> {
    type Args = R::Args;
    fn new(&self) -> impl Activation<Args = R::Args> {
        RemotingAction::<_, app_factory::io::New>::new(self.remoting.clone(), ())
    }
}

pub mod app_factory {
    use super::*;
    pub mod io {
        use super::*;
        use sails_rs::calls::ActionIo;
        pub struct New(());
        impl New {
            #[allow(dead_code)]
            pub fn encode_call() -> Vec<u8> {
                <New as ActionIo>::encode_call(&())
            }
        }
        impl ActionIo for New {
            const ROUTE: &'static [u8] = &[12, 78, 101, 119];
            type Params = ();
            type Reply = ();
        }
    }
}
pub struct TrafficLight<R> {
    remoting: R,
}
impl<R> TrafficLight<R> {
    pub fn new(remoting: R) -> Self {
        Self { remoting }
    }
}
impl<R: Remoting + Clone> traits::TrafficLight for TrafficLight<R> {
    type Args = R::Args;
    fn green(&mut self) -> impl Call<Output = TrafficLightEvent, Args = R::Args> {
        RemotingAction::<_, traffic_light::io::Green>::new(self.remoting.clone(), ())
    }
    fn red(&mut self) -> impl Call<Output = TrafficLightEvent, Args = R::Args> {
        RemotingAction::<_, traffic_light::io::Red>::new(self.remoting.clone(), ())
    }
    fn yellow(&mut self) -> impl Call<Output = TrafficLightEvent, Args = R::Args> {
        RemotingAction::<_, traffic_light::io::Yellow>::new(self.remoting.clone(), ())
    }
    fn bind_keyring_data_to_user_address(
        &mut self,
        user_address: ActorId,
        keyring_data: KeyringData,
    ) -> impl Call<Output = KeyringEvent, Args = R::Args> {
        RemotingAction::<_, traffic_light::io::BindKeyringDataToUserAddress>::new(
            self.remoting.clone(),
            (user_address, keyring_data),
        )
    }
    fn bind_keyring_data_to_user_coded_name(
        &mut self,
        user_coded_name: String,
        keyring_data: KeyringData,
    ) -> impl Call<Output = KeyringEvent, Args = R::Args> {
        RemotingAction::<_, traffic_light::io::BindKeyringDataToUserCodedName>::new(
            self.remoting.clone(),
            (user_coded_name, keyring_data),
        )
    }
    fn traffic_light(&self) -> impl Query<Output = IoTrafficLightState, Args = R::Args> {
        RemotingAction::<_, traffic_light::io::TrafficLight>::new(self.remoting.clone(), ())
    }
    fn keyring_account_data(
        &self,
        keyring_address: ActorId,
    ) -> impl Query<Output = KeyringQueryEvent, Args = R::Args> {
        RemotingAction::<_, traffic_light::io::KeyringAccountData>::new(
            self.remoting.clone(),
            keyring_address,
        )
    }
    fn keyring_address_from_user_address(
        &self,
        user_address: ActorId,
    ) -> impl Query<Output = KeyringQueryEvent, Args = R::Args> {
        RemotingAction::<_, traffic_light::io::KeyringAddressFromUserAddress>::new(
            self.remoting.clone(),
            user_address,
        )
    }
    fn keyring_address_from_user_coded_name(
        &self,
        user_coded_name: String,
    ) -> impl Query<Output = KeyringQueryEvent, Args = R::Args> {
        RemotingAction::<_, traffic_light::io::KeyringAddressFromUserCodedName>::new(
            self.remoting.clone(),
            user_coded_name,
        )
    }
}

pub mod traffic_light {
    use super::*;

    pub mod io {
        use super::*;
        use sails_rs::calls::ActionIo;
        pub struct Green(());
        impl Green {
            #[allow(dead_code)]
            pub fn encode_call() -> Vec<u8> {
                <Green as ActionIo>::encode_call(&())
            }
        }
        impl ActionIo for Green {
            const ROUTE: &'static [u8] = &[
                48, 84, 114, 97, 102, 102, 105, 99, 76, 105, 103, 104, 116, 20, 71, 114, 101, 101,
                110,
            ];
            type Params = ();
            type Reply = super::TrafficLightEvent;
        }
        pub struct Red(());
        impl Red {
            #[allow(dead_code)]
            pub fn encode_call() -> Vec<u8> {
                <Red as ActionIo>::encode_call(&())
            }
        }
        impl ActionIo for Red {
            const ROUTE: &'static [u8] = &[
                48, 84, 114, 97, 102, 102, 105, 99, 76, 105, 103, 104, 116, 12, 82, 101, 100,
            ];
            type Params = ();
            type Reply = super::TrafficLightEvent;
        }
        pub struct Yellow(());
        impl Yellow {
            #[allow(dead_code)]
            pub fn encode_call() -> Vec<u8> {
                <Yellow as ActionIo>::encode_call(&())
            }
        }
        impl ActionIo for Yellow {
            const ROUTE: &'static [u8] = &[
                48, 84, 114, 97, 102, 102, 105, 99, 76, 105, 103, 104, 116, 24, 89, 101, 108, 108,
                111, 119,
            ];
            type Params = ();
            type Reply = super::TrafficLightEvent;
        }
        pub struct BindKeyringDataToUserAddress(());
        impl BindKeyringDataToUserAddress {
            #[allow(dead_code)]
            pub fn encode_call(user_address: ActorId, keyring_data: super::KeyringData) -> Vec<u8> {
                <BindKeyringDataToUserAddress as ActionIo>::encode_call(&(
                    user_address,
                    keyring_data,
                ))
            }
        }
        impl ActionIo for BindKeyringDataToUserAddress {
            const ROUTE: &'static [u8] = &[
                48, 84, 114, 97, 102, 102, 105, 99, 76, 105, 103, 104, 116, 112, 66, 105, 110, 100,
                75, 101, 121, 114, 105, 110, 103, 68, 97, 116, 97, 84, 111, 85, 115, 101, 114, 65,
                100, 100, 114, 101, 115, 115,
            ];
            type Params = (ActorId, super::KeyringData);
            type Reply = super::KeyringEvent;
        }
        pub struct BindKeyringDataToUserCodedName(());
        impl BindKeyringDataToUserCodedName {
            #[allow(dead_code)]
            pub fn encode_call(
                user_coded_name: String,
                keyring_data: super::KeyringData,
            ) -> Vec<u8> {
                <BindKeyringDataToUserCodedName as ActionIo>::encode_call(&(
                    user_coded_name,
                    keyring_data,
                ))
            }
        }
        impl ActionIo for BindKeyringDataToUserCodedName {
            const ROUTE: &'static [u8] = &[
                48, 84, 114, 97, 102, 102, 105, 99, 76, 105, 103, 104, 116, 120, 66, 105, 110, 100,
                75, 101, 121, 114, 105, 110, 103, 68, 97, 116, 97, 84, 111, 85, 115, 101, 114, 67,
                111, 100, 101, 100, 78, 97, 109, 101,
            ];
            type Params = (String, super::KeyringData);
            type Reply = super::KeyringEvent;
        }
        pub struct TrafficLight(());
        impl TrafficLight {
            #[allow(dead_code)]
            pub fn encode_call() -> Vec<u8> {
                <TrafficLight as ActionIo>::encode_call(&())
            }
        }
        impl ActionIo for TrafficLight {
            const ROUTE: &'static [u8] = &[
                48, 84, 114, 97, 102, 102, 105, 99, 76, 105, 103, 104, 116, 48, 84, 114, 97, 102,
                102, 105, 99, 76, 105, 103, 104, 116,
            ];
            type Params = ();
            type Reply = super::IoTrafficLightState;
        }
        pub struct KeyringAccountData(());
        impl KeyringAccountData {
            #[allow(dead_code)]
            pub fn encode_call(keyring_address: ActorId) -> Vec<u8> {
                <KeyringAccountData as ActionIo>::encode_call(&keyring_address)
            }
        }
        impl ActionIo for KeyringAccountData {
            const ROUTE: &'static [u8] = &[
                48, 84, 114, 97, 102, 102, 105, 99, 76, 105, 103, 104, 116, 72, 75, 101, 121, 114,
                105, 110, 103, 65, 99, 99, 111, 117, 110, 116, 68, 97, 116, 97,
            ];
            type Params = ActorId;
            type Reply = super::KeyringQueryEvent;
        }
        pub struct KeyringAddressFromUserAddress(());
        impl KeyringAddressFromUserAddress {
            #[allow(dead_code)]
            pub fn encode_call(user_address: ActorId) -> Vec<u8> {
                <KeyringAddressFromUserAddress as ActionIo>::encode_call(&user_address)
            }
        }
        impl ActionIo for KeyringAddressFromUserAddress {
            const ROUTE: &'static [u8] = &[
                48, 84, 114, 97, 102, 102, 105, 99, 76, 105, 103, 104, 116, 116, 75, 101, 121, 114,
                105, 110, 103, 65, 100, 100, 114, 101, 115, 115, 70, 114, 111, 109, 85, 115, 101,
                114, 65, 100, 100, 114, 101, 115, 115,
            ];
            type Params = ActorId;
            type Reply = super::KeyringQueryEvent;
        }
        pub struct KeyringAddressFromUserCodedName(());
        impl KeyringAddressFromUserCodedName {
            #[allow(dead_code)]
            pub fn encode_call(user_coded_name: String) -> Vec<u8> {
                <KeyringAddressFromUserCodedName as ActionIo>::encode_call(&user_coded_name)
            }
        }
        impl ActionIo for KeyringAddressFromUserCodedName {
            const ROUTE: &'static [u8] = &[
                48, 84, 114, 97, 102, 102, 105, 99, 76, 105, 103, 104, 116, 124, 75, 101, 121, 114,
                105, 110, 103, 65, 100, 100, 114, 101, 115, 115, 70, 114, 111, 109, 85, 115, 101,
                114, 67, 111, 100, 101, 100, 78, 97, 109, 101,
            ];
            type Params = String;
            type Reply = super::KeyringQueryEvent;
        }
    }
}
#[derive(PartialEq, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum TrafficLightEvent {
    Green,
    Yellow,
    Red,
}
#[derive(PartialEq, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct KeyringData {
    pub address: String,
    pub encoded: String,
}
#[derive(PartialEq, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum KeyringEvent {
    KeyringAccountSet,
    Error(KeyringError),
}
#[derive(PartialEq, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum KeyringError {
    KeyringAddressAlreadyEsists,
    UserAddressAlreadyExists,
    UserCodedNameAlreadyExists,
    UserDoesNotHasKeyringAccount,
    KeyringAccountAlreadyExists,
    SessionHasInvalidCredentials,
    UserAndKeyringAddressAreTheSame,
}
#[derive(PartialEq, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct IoTrafficLightState {
    pub current_light: String,
    pub all_users: Vec<(ActorId, String)>,
}
#[derive(PartialEq, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum KeyringQueryEvent {
    LastWhoCall(ActorId),
    SignlessAccountAddress(Option<ActorId>),
    SignlessAccountData(Option<KeyringData>),
}

pub mod traits {
    use super::*;
    #[allow(dead_code)]
    pub trait AppFactory {
        type Args;
        #[allow(clippy::new_ret_no_self)]
        #[allow(clippy::wrong_self_convention)]
        fn new(&self) -> impl Activation<Args = Self::Args>;
    }

    #[allow(clippy::type_complexity)]
    pub trait TrafficLight {
        type Args;
        fn green(&mut self) -> impl Call<Output = TrafficLightEvent, Args = Self::Args>;
        fn red(&mut self) -> impl Call<Output = TrafficLightEvent, Args = Self::Args>;
        fn yellow(&mut self) -> impl Call<Output = TrafficLightEvent, Args = Self::Args>;
        fn bind_keyring_data_to_user_address(
            &mut self,
            user_address: ActorId,
            keyring_data: KeyringData,
        ) -> impl Call<Output = KeyringEvent, Args = Self::Args>;
        fn bind_keyring_data_to_user_coded_name(
            &mut self,
            user_coded_name: String,
            keyring_data: KeyringData,
        ) -> impl Call<Output = KeyringEvent, Args = Self::Args>;
        fn traffic_light(&self) -> impl Query<Output = IoTrafficLightState, Args = Self::Args>;
        fn keyring_account_data(
            &self,
            keyring_address: ActorId,
        ) -> impl Query<Output = KeyringQueryEvent, Args = Self::Args>;
        fn keyring_address_from_user_address(
            &self,
            user_address: ActorId,
        ) -> impl Query<Output = KeyringQueryEvent, Args = Self::Args>;
        fn keyring_address_from_user_coded_name(
            &self,
            user_coded_name: String,
        ) -> impl Query<Output = KeyringQueryEvent, Args = Self::Args>;
    }
}
